name: Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test with Pytest
      run: pip install pytest   
          
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY33 }}
        port: ${{ secrets.PORT }}
        timeout: 120s
        
        script: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx

    - name: Deploy to Digital Ocean VPS
      run: ssh root@167.71.6.124 
      
    - name: change directory
      run: cd /home/glowing-cd
      
    - name: pull and install
      run: git fetch

    - name: reset and pull
      run: git reset --hard origin/main

    - name: pull
      run: git pull

    - name: install
      run: pip install -r requirements.txt

    - name: restart service
      run: systemctl restart cd.service 
      
      
      
