name: Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.9
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.10'
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Test with Pytest
      run: pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to Digital Ocean VPS
      run: ssh root@161.35.80.203 "cd var/www/html/service.cd && git pull && pip install -r requirements.txt && systemctl restart service.cd"
