name: Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test with Pytest
      run: pip install pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.8
      with:
      
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY2 }}
    port: ${{ secrets.PORT }}
    script: whoami
    
    - name: Deploy to Digital Ocean VPS
      run: ssh root@161.35.80.203 "cd /root/glowing-cd/service.cd && git pull && systemctl restart service.cd"
