name: Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test with Pytest
      run: pip install pytest   
          
deploy:
    needs: test
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.4.1
      with:
       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to Digital Ocean VPS
      run: ssh root@161.35.80.203 
      
    - name: change directory
      run: cd /home/glowing-cd
      
    - name: pull and install
      run: |
      
      git fetch
      git reset --hard origin/main
      git pull
      pip install -r requirements.txt
      systemctl restart cd.service

      # Path: .github/workflows/deploy.yml  
